spring.application.name=backend

server.port=8080

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:novarecruit_db}?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# JWT
# ===============================
app.jwt.secret=${JWT_SECRET:uRz7F7Fq4H9d9ixOqf4P3UVAEg6b4OiQS85LSgZXy/ao=}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# ===============================
# EMAIL
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.enabled=${APP_MAIL_ENABLED:false}
app.mail.from=${MAIL_USERNAME:novarecruit@demo.com}
app.mail.from-name=NovaRecruit
app.mail.verification-expiration-minutes=15

# ===============================
# CORS / FRONTEND
# ===============================
app.cors.allowed-origins=${FRONTEND_URL:http://localhost:5173},http://127.0.0.1:5173